version: 0.0
os: linux
files:
  - source: target/HelloWorld-1.0-SNAPSHOT.jar
    destination: /usr/local/helloworld/
  - source: hello-world.yml
    destination: /usr/local/helloworld/
  - source: scripts/dw-helloworld.conf
    destination: /etc/init/
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
  ValidateService:
    - location: scripts/validate.sh
    
    
    
